name: ori
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - jupyterlab=4.0.3
  - nodejs=18.16.1
  - panel=1.2.3
  - plotly=5.15.0
  - jupytext=1.14.7
  - pyviz::hvplot=0.8.4
  - pip:
    - pyalex==0.11
    - networkx[default]==3.1
