# configuration file for jupytext

# pair ipynb notebooks with py:percent files
formats = "notebooks///ipynb,scripts///md"

# exclude metadata in scripts
notebook_metadata_filter = "kernel"
cell_metadata_filter = "-all"
