name: convert-to-website

on:
  workflow_dispatch:
  push:
    branches: 
      - 'main'
    paths:
      - 'scripts'

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Packages
        run: |
          pip install jupyterlab==4.0.3 panel==1.2.1 bokeh==3.2.1 plotly==5.15.0 jupytext==1.14.7 hvplot==0.8.4 pyalex==0.11 networkx[default]==3.1
      - name: Convert
        run: |
          jupytext --sync scripts/*
          panel convert notebooks/*.ipynb --to pyodide-worker --out docs --index --title "Open RI" --pwa
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
