name: Convert to Website

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: anaconda-client-env
          environment-file: environment-build.yml
          python-version: 3.10
      - name: Convert
        run: |
          jupytext --sync scripts/*
          panel convert notebooks/* --to pyodide-worker --out docs --index
      - name: Commit website
        run: |
          git config --global user.name 'Max Paulus'
          git config --global user.email 'paulmaxus@gmail.com'
          git add docs/*
          git commit -m "updated website"
          git push gh-pages
