name: convert-to-website

on:
  workflow_dispatch:
  push:
    branches: main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Packages
        run: |
          pip install notebook
          pip install panel
          pip install plotly
          pip install jupytext
      - name: Convert
        run: |
          jupytext --sync scripts/*
          panel convert notebooks/*.ipynb --to pyodide-worker --out docs --index
      - name: Deploy
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: gh-pages
          FOLDER: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
